INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (1, 'tokyo-sakura-5days', '東京櫻花五日：新宿、上野、河口湖賞櫻深度之旅', '三月底四月初櫻花季限定，走訪新宿御苑、上野公園、河口湖，近距離眺望富士山與盛開櫻花。', 5, 'published', 1, 1, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (2, 'kyoto-autumn-6days', '京都賞楓六日：清水寺、嵐山、伏見稻荷古都巡禮', '十一月楓紅正盛，深度走訪清水寺、嵐山竹林、伏見稻荷千本鳥居，體驗古都秋日風情。', 6, 'published', 1, 2, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (3, 'hokkaido-onsen-5days', '北海道溫泉美食五日：登別、小樽、札幌雪國饗宴', '冬季限定，登別地獄谷溫泉、小樽運河、札幌湯咖哩與海鮮市場，暖心暖胃的北國之旅。', 5, 'published', 0, 3, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (4, 'seoul-family-4days', '首爾親子四日：樂天世界、南山塔輕鬆遊', '安排大量親子友善景點與適度自由活動時間，適合帶小朋友一起出遊的家庭行程。', 4, 'published', 0, 4, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (5, 'taipei-101-food-3days', '台北深度小旅行三日：101、在地美食巡禮', '獻給國旅愛好者的台北深度行程，走訪信義區、大稻埕，品嚐在地小吃與精緻餐廳。', 3, 'published', 0, 5, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO trips (id, slug, title, summary, days, status, is_featured, rank, created_at, updated_at) VALUES (6, 'kyoto-spring-draft', '京都春季試辦行程（草稿）', '尚在規劃中的春季行程草稿，內容尚未確認，不對外公開。', 5, 'draft', 0, 0, '2026-08-08 14:39:25', '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (1, 1, '2027-03-25', '2027-03-29', 'CI 桃園-成田 直飛', '桃園機場第二航廈', 'NT$ 42,900 起', 20, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (2, 1, '2027-04-01', '2027-04-05', 'BR 桃園-成田 直飛', '桃園機場第一航廈', 'NT$ 45,900 起', 20, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (3, 2, '2026-11-14', '2026-11-19', 'JX 桃園-關西 直飛', '桃園機場第一航廈', 'NT$ 52,900 起', 16, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (4, 2, '2026-11-21', '2026-11-26', 'CI 桃園-關西 直飛', '桃園機場第二航廈', 'NT$ 54,900 起', 16, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (5, 3, '2027-01-10', '2027-01-14', 'CI 桃園-新千歲 直飛', '桃園機場第二航廈', 'NT$ 46,900 起', 18, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (6, 4, '2026-10-02', '2026-10-05', 'BR 桃園-仁川 直飛', '桃園機場第一航廈', 'NT$ 28,900 起', 20, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (7, 4, '2026-12-27', '2026-12-30', 'CI 桃園-仁川 直飛', '桃園機場第二航廈', 'NT$ 31,900 起', 20, '2026-08-08 14:39:25');
INSERT INTO batches (id, trip_id, departure_date, return_date, flight_info, meeting_point, price_info, group_size, created_at) VALUES (8, 5, '2026-09-18', '2026-09-20', '無需搭機（國旅巴士接送）', '台北車站東三門', 'NT$ 8,900 起', 25, '2026-08-08 14:39:25');
INSERT INTO tags (id, name, category) VALUES (1, '日本', 'location');
INSERT INTO tags (id, name, category) VALUES (2, '東京', 'location');
INSERT INTO tags (id, name, category) VALUES (3, '京都', 'location');
INSERT INTO tags (id, name, category) VALUES (4, '北海道', 'location');
INSERT INTO tags (id, name, category) VALUES (5, '韓國', 'location');
INSERT INTO tags (id, name, category) VALUES (6, '台灣', 'location');
INSERT INTO tags (id, name, category) VALUES (7, '富士山', 'attraction');
INSERT INTO tags (id, name, category) VALUES (8, '清水寺', 'attraction');
INSERT INTO tags (id, name, category) VALUES (9, '101', 'attraction');
INSERT INTO tags (id, name, category) VALUES (10, '賞花', 'type');
INSERT INTO tags (id, name, category) VALUES (11, '賞楓', 'type');
INSERT INTO tags (id, name, category) VALUES (12, '美食', 'type');
INSERT INTO tags (id, name, category) VALUES (13, '親子', 'type');
INSERT INTO tags (id, name, category) VALUES (14, '深度旅遊', 'type');
INSERT INTO tags (id, name, category) VALUES (15, '溫泉', 'type');
INSERT INTO trip_tags (trip_id, tag_id) VALUES (1, 1);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (1, 2);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (1, 7);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (1, 10);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (2, 1);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (2, 3);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (2, 8);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (2, 11);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (2, 14);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (3, 1);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (3, 4);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (3, 15);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (3, 12);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (4, 5);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (4, 13);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (5, 6);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (5, 9);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (5, 12);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (5, 14);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (6, 1);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (6, 3);
INSERT INTO trip_tags (trip_id, tag_id) VALUES (6, 10);
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (1, 'trips/tokyo-sakura-5days/cover.jpg', 'https://picsum.photos/seed/tokyo-sakura-5days/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (2, 'trips/tokyo-sakura-5days/gallery-1.jpg', 'https://picsum.photos/seed/tokyo-sakura-5days-1/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (3, 'trips/tokyo-sakura-5days/gallery-2.jpg', 'https://picsum.photos/seed/tokyo-sakura-5days-2/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (4, 'trips/tokyo-sakura-5days/gallery-3.jpg', 'https://picsum.photos/seed/tokyo-sakura-5days-3/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (5, 'trips/kyoto-autumn-6days/cover.jpg', 'https://picsum.photos/seed/kyoto-autumn-6days/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (6, 'trips/kyoto-autumn-6days/gallery-1.jpg', 'https://picsum.photos/seed/kyoto-autumn-6days-1/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (7, 'trips/kyoto-autumn-6days/gallery-2.jpg', 'https://picsum.photos/seed/kyoto-autumn-6days-2/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (8, 'trips/kyoto-autumn-6days/gallery-3.jpg', 'https://picsum.photos/seed/kyoto-autumn-6days-3/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (9, 'trips/hokkaido-onsen-5days/cover.jpg', 'https://picsum.photos/seed/hokkaido-onsen-5days/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (10, 'trips/hokkaido-onsen-5days/gallery-1.jpg', 'https://picsum.photos/seed/hokkaido-onsen-5days-1/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (11, 'trips/hokkaido-onsen-5days/gallery-2.jpg', 'https://picsum.photos/seed/hokkaido-onsen-5days-2/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (12, 'trips/hokkaido-onsen-5days/gallery-3.jpg', 'https://picsum.photos/seed/hokkaido-onsen-5days-3/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (13, 'trips/seoul-family-4days/cover.jpg', 'https://picsum.photos/seed/seoul-family-4days/1200/800', '韓國', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (14, 'trips/seoul-family-4days/gallery-1.jpg', 'https://picsum.photos/seed/seoul-family-4days-1/1200/800', '韓國', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (15, 'trips/seoul-family-4days/gallery-2.jpg', 'https://picsum.photos/seed/seoul-family-4days-2/1200/800', '韓國', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (16, 'trips/seoul-family-4days/gallery-3.jpg', 'https://picsum.photos/seed/seoul-family-4days-3/1200/800', '韓國', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (17, 'trips/taipei-101-food-3days/cover.jpg', 'https://picsum.photos/seed/taipei-101-food-3days/1200/800', '台灣', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (18, 'trips/taipei-101-food-3days/gallery-1.jpg', 'https://picsum.photos/seed/taipei-101-food-3days-1/1200/800', '台灣', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (19, 'trips/taipei-101-food-3days/gallery-2.jpg', 'https://picsum.photos/seed/taipei-101-food-3days-2/1200/800', '台灣', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (20, 'trips/taipei-101-food-3days/gallery-3.jpg', 'https://picsum.photos/seed/taipei-101-food-3days-3/1200/800', '台灣', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (21, 'trips/kyoto-spring-draft/cover.jpg', 'https://picsum.photos/seed/kyoto-spring-draft/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (22, 'trips/kyoto-spring-draft/gallery-1.jpg', 'https://picsum.photos/seed/kyoto-spring-draft-1/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (23, 'trips/kyoto-spring-draft/gallery-2.jpg', 'https://picsum.photos/seed/kyoto-spring-draft-2/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO media (id, r2_key, url, category, created_at) VALUES (24, 'trips/kyoto-spring-draft/gallery-3.jpg', 'https://picsum.photos/seed/kyoto-spring-draft-3/1200/800', '日本', '2026-08-08 14:39:25');
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (1, 1, 1, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (2, 1, 2, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (3, 1, 3, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (4, 1, 4, 0, 3);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (5, 2, 5, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (6, 2, 6, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (7, 2, 7, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (8, 2, 8, 0, 3);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (9, 3, 9, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (10, 3, 10, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (11, 3, 11, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (12, 3, 12, 0, 3);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (13, 4, 13, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (14, 4, 14, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (15, 4, 15, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (16, 4, 16, 0, 3);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (17, 5, 17, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (18, 5, 18, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (19, 5, 19, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (20, 5, 20, 0, 3);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (21, 6, 21, 1, 0);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (22, 6, 22, 0, 1);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (23, 6, 23, 0, 2);
INSERT INTO trip_images (id, trip_id, media_id, is_cover, sort_order) VALUES (24, 6, 24, 0, 3);
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (1, 1, 'highlights', 0, '{"html":"<p><strong>經典賞櫻路線</strong> ~ 新宿御苑、上野公園、河口湖三大賞櫻名所一次收藏</p><p>本行程專為賞櫻旺季規劃，避開人潮擁擠的熱門時段，並前往河口湖眺望富士山與湖畔櫻花並列的經典畫面。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (2, 1, 'flight', 1, '{"legs":[{"label":"去程","date":"2027-03-25","airline":"中華航空","fromCode":"TPE","fromName":"桃園機場","toCode":"NRT","toName":"東京成田機場","departTime":"08:30","arriveTime":"12:55","duration":"3h25m"},{"label":"回程","date":"2027-03-29","airline":"中華航空","fromCode":"NRT","fromName":"東京成田機場","toCode":"TPE","toName":"桃園機場","departTime":"14:10","arriveTime":"16:50","duration":"3h40m"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (3, 1, 'daily_itinerary', 2, '{"days":[{"day":1,"title":"桃園機場 → 東京成田機場 → 入住新宿飯店","html":"<p>集合於桃園機場，搭乘豪華客機飛往東京成田機場，抵達後專車前往新宿地區辦理入住。</p>","meals":{"breakfast":"","lunch":"","dinner":"機上精緻簡餐"},"hotel":"新宿華盛頓飯店或同級"},{"day":2,"title":"新宿御苑賞櫻 → 明治神宮 → 表參道自由活動","html":"<p>上午前往新宿御苑漫步賞櫻，隨後參觀明治神宮，下午於表參道自由活動、逛街購物。</p>","meals":{"breakfast":"飯店內早餐","lunch":"日式定食料理","dinner":""},"hotel":"新宿華盛頓飯店或同級"},{"day":3,"title":"河口湖畔賞櫻 → 富士山展望 → 溫泉飯店住宿","html":"<p>專車前往河口湖，欣賞富士山與湖畔櫻花並列的經典畫面，晚間入住溫泉飯店放鬆身心。</p>","meals":{"breakfast":"飯店內早餐","lunch":"湖畔餐廳","dinner":"溫泉飯店會席料理"},"hotel":"河口湖溫泉飯店或同級"},{"day":4,"title":"上野公園賞櫻 → 淺草寺 → 台場自由活動","html":"<p>上午於上野公園賞櫻，參觀淺草寺雷門，下午於台場自由活動。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"新宿華盛頓飯店或同級"},{"day":5,"title":"成田機場 → 桃園機場","html":"<p>專車前往成田機場，搭機返回溫暖的家。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"溫暖的家"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (4, 2, 'highlights', 0, '{"html":"<p><strong>深度慢旅</strong> ~ 六天五夜完整停留京都，避開走馬看花的緊湊行程</p><p>京都是日本賞楓最具代表性的城市，讓旅客有充分時間感受古都氛圍。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (5, 2, 'flight', 1, '{"legs":[{"label":"去程","date":"2026-11-14","airline":"星宇航空","fromCode":"TPE","fromName":"桃園機場","toCode":"KIX","toName":"大阪關西機場","departTime":"09:10","arriveTime":"12:40","duration":"3h30m"},{"label":"回程","date":"2026-11-19","airline":"星宇航空","fromCode":"KIX","fromName":"大阪關西機場","toCode":"TPE","toName":"桃園機場","departTime":"13:40","arriveTime":"16:00","duration":"3h20m"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (6, 2, 'daily_itinerary', 2, '{"days":[{"day":1,"title":"桃園機場 → 大阪關西機場 → 京都入住","html":"<p>搭機飛往大阪關西機場，專車接送前往京都入住。</p>","meals":{"breakfast":"","lunch":"","dinner":"機上精緻簡餐"},"hotel":"京都站前飯店或同級"},{"day":2,"title":"清水寺 → 二年坂三年坂 → 祇園花見小路","html":"<p>參觀世界遺產清水寺，漫步二年坂三年坂，於祇園花見小路感受古都風情。</p>","meals":{"breakfast":"飯店內早餐","lunch":"京都風味料理","dinner":""},"hotel":"京都站前飯店或同級"},{"day":3,"title":"嵐山竹林小徑 → 渡月橋 → 天龍寺","html":"<p>走訪嵐山竹林小徑、渡月橋，參觀世界遺產天龍寺庭園。</p>","meals":{"breakfast":"飯店內早餐","lunch":"嵐山湯豆腐料理","dinner":""},"hotel":"京都站前飯店或同級"},{"day":4,"title":"伏見稻荷大社千本鳥居 → 東福寺賞楓","html":"<p>參拜伏見稻荷大社千本鳥居，前往東福寺欣賞楓紅美景。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"京都站前飯店或同級"},{"day":5,"title":"奈良公園 → 東大寺 → 大阪心齋橋自由活動","html":"<p>前往奈良公園與小鹿互動，參觀東大寺，晚間於大阪心齋橋自由活動。</p>","meals":{"breakfast":"飯店內早餐","lunch":"奈良鄉土料理","dinner":""},"hotel":"大阪市區飯店或同級"},{"day":6,"title":"大阪關西機場 → 桃園機場","html":"<p>專車前往關西機場，搭機返回溫暖的家。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"溫暖的家"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (7, 3, 'highlights', 0, '{"html":"<p><strong>雪國美食巡禮</strong> ~ 連續兩晚溫泉飯店住宿，深度品嚐北海道在地美食</p><p>寒冬中最療癒的旅程，包含湯咖哩、成吉思汗烤肉與二條市場現撈海鮮。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (8, 3, 'flight', 1, '{"legs":[{"label":"去程","date":"2027-01-10","airline":"中華航空","fromCode":"TPE","fromName":"桃園機場","toCode":"CTS","toName":"新千歲機場","departTime":"07:50","arriveTime":"12:30","duration":"4h40m"},{"label":"回程","date":"2027-01-14","airline":"中華航空","fromCode":"CTS","fromName":"新千歲機場","toCode":"TPE","toName":"桃園機場","departTime":"13:50","arriveTime":"17:20","duration":"4h30m"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (9, 3, 'daily_itinerary', 2, '{"days":[{"day":1,"title":"桃園機場 → 新千歲機場 → 登別溫泉","html":"<p>搭機飛往新千歲機場，專車前往登別溫泉區入住。</p>","meals":{"breakfast":"","lunch":"","dinner":"溫泉飯店會席料理"},"hotel":"登別溫泉飯店或同級"},{"day":2,"title":"登別地獄谷 → 熊牧場 → 洞爺湖溫泉","html":"<p>參觀登別地獄谷、熊牧場，晚間入住洞爺湖溫泉飯店。</p>","meals":{"breakfast":"飯店內早餐","lunch":"成吉思汗烤肉","dinner":""},"hotel":"洞爺湖溫泉飯店或同級"},{"day":3,"title":"小樽運河 → 音樂盒博物館 → 札幌市區","html":"<p>漫步小樽運河、參觀音樂盒博物館，晚間入住札幌市區。</p>","meals":{"breakfast":"飯店內早餐","lunch":"小樽壽司","dinner":""},"hotel":"札幌市區飯店或同級"},{"day":4,"title":"白色戀人公園 → 二條市場 → 狸小路自由活動","html":"<p>參觀白色戀人公園，於二條市場品嚐現撈海鮮，晚間於狸小路自由活動。</p>","meals":{"breakfast":"飯店內早餐","lunch":"湯咖哩","dinner":""},"hotel":"札幌市區飯店或同級"},{"day":5,"title":"新千歲機場 → 桃園機場","html":"<p>專車前往新千歲機場，搭機返回溫暖的家。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"溫暖的家"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (10, 4, 'highlights', 0, '{"html":"<p><strong>輕鬆親子遊</strong> ~ 行程步調放緩，安排樂天世界、兒童大公園等親子景點</p><p>飯店選擇皆鄰近地鐵站，方便親子移動。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (11, 4, 'flight', 1, '{"legs":[{"label":"去程","date":"2026-10-02","airline":"長榮航空","fromCode":"TPE","fromName":"桃園機場","toCode":"ICN","toName":"仁川機場","departTime":"09:00","arriveTime":"12:15","duration":"2h15m"},{"label":"回程","date":"2026-10-05","airline":"長榮航空","fromCode":"ICN","fromName":"仁川機場","toCode":"TPE","toName":"桃園機場","departTime":"13:20","arriveTime":"15:40","duration":"2h20m"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (12, 4, 'daily_itinerary', 2, '{"days":[{"day":1,"title":"桃園機場 → 仁川機場 → 首爾入住","html":"<p>搭機飛往仁川機場，專車前往首爾市區入住。</p>","meals":{"breakfast":"","lunch":"","dinner":"機上精緻簡餐"},"hotel":"首爾市區飯店或同級"},{"day":2,"title":"樂天世界 → 石村湖公園","html":"<p>整日暢遊樂天世界主題樂園，午後於石村湖公園散步。</p>","meals":{"breakfast":"飯店內早餐","lunch":"園區內自理","dinner":""},"hotel":"首爾市區飯店或同級"},{"day":3,"title":"南山首爾塔 → 明洞自由活動","html":"<p>登上南山首爾塔欣賞市景，午後於明洞自由活動、購物。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"首爾市區飯店或同級"},{"day":4,"title":"仁川機場 → 桃園機場","html":"<p>專車前往仁川機場，搭機返回溫暖的家。</p>","meals":{"breakfast":"飯店內早餐","lunch":"","dinner":""},"hotel":"溫暖的家"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (13, 5, 'highlights', 0, '{"html":"<p><strong>國旅深度行程</strong> ~ 適合外縣市旅客或想在地深度旅遊的旅客</p><p>安排 101 觀景台、大稻埕迪化街與多家在地口碑美食。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (14, 5, 'daily_itinerary', 1, '{"days":[{"day":1,"title":"集合 → 大稻埕迪化街 → 寧夏夜市","html":"<p>台北車站集合，漫步大稻埕迪化街，晚間於寧夏夜市享用道地小吃。</p>","meals":{"breakfast":"","lunch":"","dinner":"寧夏夜市小吃"},"hotel":"台北市區飯店或同級"},{"day":2,"title":"台北101觀景台 → 象山步道 → 信義區自由活動","html":"<p>登上台北101觀景台，健行象山步道欣賞市景，午後於信義區自由活動。</p>","meals":{"breakfast":"飯店內早餐","lunch":"信義區餐廳","dinner":""},"hotel":"台北市區飯店或同級"},{"day":3,"title":"故宮博物院 → 士林夜市 → 賦歸","html":"<p>參觀故宮博物院國寶文物，午後於士林夜市採買伴手禮後賦歸。</p>","meals":{"breakfast":"飯店內早餐","lunch":"士林夜市小吃","dinner":""},"hotel":"賦歸"}]}', '2026-08-08 14:39:25');
INSERT INTO content_blocks (id, trip_id, type, sort_order, data, created_at) VALUES (15, 6, 'richtext', 0, '{"html":"<p>行程細節尚未確認，僅供後台編輯測試草稿/發布功能。</p>"}', '2026-08-08 14:39:25');
INSERT INTO content_snippets (id, name, type, data, created_at) VALUES (1, '出國旅遊安全須知', 'richtext', '{"html":"<p><strong>出國旅遊安全須知</strong></p><p>1. 請於出發前確認護照效期至少 6 個月以上。</p><p>2. 建議自行投保旅遊平安險及不便險。</p><p>3. 隨身攜帶緊急聯絡卡與旅行社 24 小時緊急聯絡電話。</p><p>4. 貴重物品請隨身攜帶，勿置於托運行李中。</p>"}', '2026-08-08 14:39:25');
INSERT INTO hero_content (id, title, subtitle, image_url, updated_at) VALUES (1, '無穹旅行社', '帶你走進每一段值得記住的旅程', 'https://picsum.photos/seed/hero-main/1920/1080', '2026-08-08 14:39:25');
INSERT INTO contact_submissions (id, name, phone, email, interested_trip_id, message, created_at) VALUES (1, '陳小姐', '0912-345-678', 'chen@example.com', 1, '請問三月底的東京賞櫻團還有名額嗎？想幫爸媽報名兩位。', '2026-08-08 14:39:25');
INSERT INTO contact_submissions (id, name, phone, email, interested_trip_id, message, created_at) VALUES (2, '林先生', '0922-111-222', NULL, NULL, '想詢問是否有規劃沖繩親子行程，預計明年暑假出發。', '2026-08-08 14:39:25');
